export const SET_PRODUCTS = 'SET_PRODUCTS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const REDUCE_QUANTITY_IN_CART = 'REDUCE_QUANTITY_IN_CART';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
